name: Run Python Script

#on:
#  schedule:
#    - cron: '0 18 * * *'

on: push

permissions:
  contents: write

jobs:
  autoscrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # May use v2

    - name: Set up Python
      uses: actions/setup-python@v4 # May use v2
      with:
        python-version: 3.9  # Choosen Python version

    - name: Install dependencies
      run: python -m pip install datetime bs4 selenium pandas webdriver_manager # Replace with your own dependency installation command
      #time
      #selenium.webdriver.common.keys
      #selenium.webdriver.common.by
      #selenium.webdriver.support.ui
      #webdriver_manager.chrome
      #webdriver_manager.core.os_manager

    - name: Run Python script
      run: python scrape.py

    # Add new files in data folder, commit along with other modified files, push
    - name: Commit files
      run: |
        git config --local user.name actions-user
        git config --local user.email "actions@github.com"
        git add data/*
        git commit -am "GH ACTION Headlines $(date)"
        git push origin main
      env:
        REPO_KEY: ${{secrets.GITHUB_TOKEN}}
        username: github-actions
        
